"""
IL-09 Election Night Main Loop
===============================
Runs on election night starting at or before 7:00 PM.

Usage:
    python main.py

Requires:
    - poll_baseline.json in project root (generated by win_probability_simulator.py)
    - .env with BSKY_HANDLE and BSKY_APP_PASSWORD
    - Cook County contestId set in Cook_County_Scraper.py
    - Chicago BOE scraper built day-of and imported below

Flow (every 30 seconds):
    1. Fetch all four jurisdictions
    2. Merge into district-wide totals
    3. Build blended baseline (actual votes + poll prior for unreported)
    4. Run 10,000-iteration Monte Carlo
    5. Check elimination and win-probability triggers
    6. Post to Bluesky every 5 minutes or immediately on trigger
"""

import json
import time
import numpy as np
from datetime import datetime

# ── Local imports ────────────────────────────────────────────────────────────
# Simulation engine — pull only what we need from the existing simulator
from win_probability_simulator import (
    simulate_election,
    CANDIDATES,
)

# Scrapers
from Cook_County_Scraper import CookCountyScraper
from mchenry_lake import LakeMcHenryScraper
from cook_precinct_expectations import CookPrecinctExpectations

# Bluesky bot
from bluesky_bot import BlueskyBot
from election_logger import ElectionLogger

# Chicago BOE scraper — build day-of; stub provided below so the rest
# of the file can be written and tested beforehand.
try:
    from chicago_boe_scraper import fetch_chicago
except ImportError:
    def fetch_chicago():
        """
        Stub — replace with real scraper on election day.
        Returns the same shape as the real scraper will:
            {
                'precincts_reported': int,
                'total_precincts':    int,
                'candidates': {
                    'Biss':          {'votes': int, 'pct': float},
                    'Abughazaleh':   {'votes': int, 'pct': float},
                    ...
                }
            }
        """
        return {
            'precincts_reported': 0,
            'total_precincts': 822,
            'candidates': {c: {'votes': 0, 'pct': 0.0} for c in CANDIDATES},
        }


# ── Configuration ─────────────────────────────────────────────────────────────

POLL_BASELINE_FILE = 'poll_baseline.json'

POLL_INTERVAL_SECONDS   = 30    # how often to scrape
POST_INTERVAL_SECONDS   = 300   # how often to post (5 minutes)
N_SIM_ITERATIONS        = 10_000

# Precinct totals per jurisdiction (used to weight pct_reported)
TOTAL_PRECINCTS = {
    'chicago':  822,
    'cook':     222,   # Evanston + suburban Cook in IL-09
    'lake':     None,  # civicAPI reports pct directly; set to None to use API value
    'mchenry':  None,
}

# Expected vote-share weights per jurisdiction (for district-wide blending)
JURISDICTION_VOTE_WEIGHT = {
    'chicago': 0.387,
    'cook':    0.497,
    'lake':    0.056,
    'mchenry': 0.060,
}

# Display threshold: don't show win-probability calls until enough is in
# (district ≥50% AND Chicago ≥25% AND Cook ≥25%)
DISPLAY_THRESHOLD = {
    'district': 50.0,
    'chicago':  25.0,
    'cook':     25.0,
}

# Win-probability call threshold
WIN_PROB_CALL_THRESHOLD = 97.0

# Minimum district pct reporting before elimination logic activates
MIN_REPORTING_FOR_ELIMINATION = 0.20

# Mathematical elimination: a candidate is eliminated when even their
# p90 ceiling (best realistic scenario) cannot beat the current leader's floor
ELIMINATION_CEILING_PERCENTILE = 90


# ── Load poll baseline (once at startup) ──────────────────────────────────────

def load_poll_baseline(path=POLL_BASELINE_FILE):
    with open(path, 'r') as f:
        data = json.load(f)
    current = data['current']
    return {
        'baseline':        current['baseline'],          # {cand: pct}
        'undecided_pct':   current['undecided_pct'],
        'avg_moe':         current['avg_moe'],
        'composite_weights': _build_composite_weights(current),
        'transfer_matrix': current.get('second_choice_transfer_matrix'),
        'no_second_rates': current.get('second_choice_no_second_rates'),
    }


def _build_composite_weights(current):
    """
    Reconstruct composite_weights dict from poll_baseline.json.
    Falls back to favorability weights alone if crosstabs missing.
    """
    fav = current.get('favorability_weights', {})
    return {c: fav.get(c, 1.0) for c in CANDIDATES}


# ── Jurisdiction fetching ─────────────────────────────────────────────────────

def fetch_all_jurisdictions(cook_scraper, lm_scraper):
    """
    Returns a dict with one entry per jurisdiction, each shaped as:
        {
            'precincts_reported': int,
            'total_precincts':    int,       # None if unknown
            'pct_reported':       float,     # 0.0–1.0
            'candidates': {name: {'votes': int, 'pct': float}, ...}
        }
    """
    results = {}

    # Chicago
    try:
        chi = fetch_chicago()
        # Support either pct_reported or pct_reporting key name from the real scraper
        if 'pct_reported' not in chi:
            total = chi.get('total_precincts') or TOTAL_PRECINCTS['chicago']
            chi['pct_reported'] = chi['precincts_reported'] / total if total else 0.0
        results['chicago'] = chi
    except Exception as e:
        print(f"[{_ts()}] Chicago fetch error: {e}")
        results['chicago'] = _empty_jurisdiction(TOTAL_PRECINCTS['chicago'])

    # Cook County
    _cook_raw = None
    try:
        _cook_raw = cook_scraper.fetch()
        results['cook'] = _normalize_cook(_cook_raw)
    except Exception as e:
        print(f"[{_ts()}] Cook fetch error: {e}")
        results['cook'] = _empty_jurisdiction(TOTAL_PRECINCTS['cook'])

    # Lake + McHenry (civicAPI)
    try:
        lm = lm_scraper.fetch()
        if lm:
            results['lake']    = _normalize_lm_county(lm['lake'])
            results['mchenry'] = _normalize_lm_county(lm['mchenry'])
        else:
            raise ValueError("civicAPI returned None")
    except Exception as e:
        print(f"[{_ts()}] Lake/McHenry fetch error: {e}")
        results['lake']    = _empty_jurisdiction(None)
        results['mchenry'] = _empty_jurisdiction(None)

    return results, _cook_raw


def _empty_jurisdiction(total_precincts):
    return {
        'precincts_reported': 0,
        'total_precincts':    total_precincts,
        'pct_reported':       0.0,
        'candidates':         {c: {'votes': 0, 'pct': 0.0} for c in CANDIDATES},
    }


def _normalize_cook(cook_data):
    """
    Converts CookCountyScraper output to standard jurisdiction shape.
    Cook returns totals as {candidate_name: votes} under 'totals'.
    """
    totals = cook_data.get('totals', {})
    total_votes = max(sum(totals.values()), 1)
    normalized_cands = {
        name: {'votes': votes, 'pct': votes / total_votes * 100}
        for name, votes in totals.items()
        if name in CANDIDATES
    }
    # Pad missing candidates
    for c in CANDIDATES:
        if c not in normalized_cands:
            normalized_cands[c] = {'votes': 0, 'pct': 0.0}
    return {
        'precincts_reported': cook_data.get('precincts_reporting', 0),
        'total_precincts':    cook_data.get('total_precincts'),
        'pct_reported':       cook_data.get('pct_reporting', 0.0),
        'candidates':         normalized_cands,
    }


def _normalize_lm_county(county_data):
    """
    Converts LakeMcHenryScraper output shape:
        {'candidates': {name: votes}, 'pct_reporting': float}
    to the standard jurisdiction shape used by main.py:
        {'candidates': {name: {'votes': int, 'pct': float}}, 'pct_reported': float, ...}
    """
    raw_cands = county_data.get('candidates', {})
    total = max(sum(raw_cands.values()), 1)
    normalized_cands = {
        name: {'votes': votes, 'pct': votes / total * 100}
        for name, votes in raw_cands.items()
    }
    pct = county_data.get('pct_reporting', 0.0)
    return {
        'precincts_reported': None,   # civicAPI doesn't expose precinct count
        'total_precincts':    None,
        'pct_reported':       pct,
        'candidates':         normalized_cands,
    }


# ── District-wide merge ───────────────────────────────────────────────────────

def merge_district(jurisdictions):
    """
    Merges jurisdiction results into a single district-wide view.

    Returns:
        {
            'pct_reported': float,          # weighted district-wide
            'jurisdiction_pct': {...},      # per-jurisdiction pct reported
            'votes': {cand: int},           # raw vote totals
            'actual_share': {cand: float},  # actual % of votes cast so far
            'jurisdiction_share': {         # per-jurisdiction actual share
                'chicago': {cand: float}, ...
            },
        }
    """
    total_votes = {c: 0 for c in CANDIDATES}
    jurisdiction_share = {}
    jurisdiction_pct = {}

    for jname, jdata in jurisdictions.items():
        cands = jdata.get('candidates', {})
        j_total = sum(cands[c]['votes'] for c in CANDIDATES if c in cands)

        if j_total > 0:
            jurisdiction_share[jname] = {
                c: (cands[c]['votes'] / j_total * 100) if c in cands else 0.0
                for c in CANDIDATES
            }
        else:
            jurisdiction_share[jname] = {c: 0.0 for c in CANDIDATES}

        jurisdiction_pct[jname] = jdata.get('pct_reported', 0.0)

        for c in CANDIDATES:
            if c in cands:
                total_votes[c] += cands[c]['votes']

    grand_total = sum(total_votes.values())
    actual_share = (
        {c: total_votes[c] / grand_total * 100 for c in CANDIDATES}
        if grand_total > 0
        else {c: 0.0 for c in CANDIDATES}
    )

    # District-wide pct_reported: weighted average across jurisdictions
    district_pct = sum(
        jurisdiction_pct.get(j, 0.0) * JURISDICTION_VOTE_WEIGHT[j]
        for j in JURISDICTION_VOTE_WEIGHT
    )

    return {
        'pct_reported':        district_pct,
        'jurisdiction_pct':    jurisdiction_pct,
        'votes':               total_votes,
        'actual_share':        actual_share,
        'jurisdiction_share':  jurisdiction_share,
    }


# ── Blended baseline ──────────────────────────────────────────────────────────

def build_blended_baseline(actual_share, poll_baseline, pct_reported,
                            cook_blended=None, cook_weight=0.497):
    """
    Blends observed vote shares with poll priors.

    For Cook County specifically, if cook_blended is provided, uses the
    precinct-level blended shares (actual reported + model for unreported)
    rather than the district-wide actual_share. This is more accurate
    because it accounts for which specific precincts have reported.

    For all other jurisdictions, uses the simple sqrt-weighted blend.

    As pct_reported → 1.0 the blended baseline converges to actual results.
    As pct_reported → 0.0 it stays at the poll prior.
    """
    w = min(pct_reported ** 0.5, 1.0)   # sqrt blend weight for non-Cook

    if cook_blended is not None:
        # Reconstruct district share replacing Cook component with precinct-blended
        # Other jurisdictions still use simple actual_share blend
        non_cook_weight = 1.0 - cook_weight
        blended = {}
        for c in CANDIDATES:
            # Cook contribution: precinct-level blended (already accounts for
            # unreported precincts via model, so use directly weighted by cook_weight)
            cook_contrib = cook_blended.get(c, poll_baseline[c]) * cook_weight
            # Non-Cook contribution: sqrt blend of actual vs poll prior
            non_cook_actual = actual_share.get(c, poll_baseline[c])
            non_cook_contrib = (
                w * non_cook_actual + (1 - w) * poll_baseline[c]
            ) * non_cook_weight
            blended[c] = cook_contrib + non_cook_contrib
        # Re-normalize to 100%
        total = sum(blended.values())
        if total > 0:
            blended = {c: blended[c] / total * 100 for c in CANDIDATES}
        return blended
    else:
        w = min(pct_reported ** 0.5, 1.0)
        return {
            c: w * actual_share.get(c, poll_baseline[c]) + (1 - w) * poll_baseline[c]
            for c in CANDIDATES
        }


# ── Monte Carlo (election night version) ─────────────────────────────────────

def run_election_night_simulation(blended_baseline, poll_params, n=N_SIM_ITERATIONS):
    """
    Runs n simulations using the blended baseline.
    Returns win_probs {cand: float 0-100} and ceiling {cand: p90}.
    """
    undecided_pct    = poll_params['undecided_pct']
    avg_moe          = poll_params['avg_moe']
    composite_weights = poll_params['composite_weights']
    transfer_matrix  = poll_params['transfer_matrix']
    no_second_rates  = poll_params['no_second_rates']

    # Trend signal is zeroed on election night — actual votes are the signal
    trend_signal = {c: 0.0 for c in CANDIDATES}

    wins       = {c: 0   for c in CANDIDATES}
    all_shares = {c: []  for c in CANDIDATES}

    for _ in range(n):
        result = simulate_election(
            blended_baseline,
            undecided_pct,
            avg_moe,
            trend_signal,
            composite_weights,
            transfer_matrix,
            no_second_rates,
        )
        winner = max(
            ((c, result[c]) for c in CANDIDATES),
            key=lambda x: x[1]
        )[0]
        wins[winner] += 1
        for c in CANDIDATES:
            all_shares[c].append(result.get(c, 0.0))

    win_probs = {c: wins[c] / n * 100 for c in CANDIDATES}
    ceiling   = {c: float(np.percentile(all_shares[c], ELIMINATION_CEILING_PERCENTILE))
                 for c in CANDIDATES}

    return win_probs, ceiling


# ── Elimination check ─────────────────────────────────────────────────────────

def check_eliminations(win_probs, ceiling, eliminated):
    """
    A candidate is newly eliminated if:
      - Their win probability rounds to 0.0 AND
      - Their ceiling (p90) is below the leader's current expected share AND
      - They haven't already been eliminated.

    Returns set of newly eliminated candidate names.
    """
    leader_share = max(win_probs[c] for c in CANDIDATES)
    newly_eliminated = set()

    for c in CANDIDATES:
        if c in eliminated:
            continue
        if win_probs[c] < 0.05 and ceiling[c] < (leader_share * 0.5):
            newly_eliminated.add(c)

    return newly_eliminated


# ── Display threshold check ───────────────────────────────────────────────────

def thresholds_met(merged):
    return (
        merged['pct_reported']                            >= DISPLAY_THRESHOLD['district'] / 100
        and merged['jurisdiction_pct'].get('chicago', 0) >= DISPLAY_THRESHOLD['chicago'] / 100
        and merged['jurisdiction_pct'].get('cook', 0)    >= DISPLAY_THRESHOLD['cook'] / 100
    )


# ── Helpers ───────────────────────────────────────────────────────────────────

def _ts():
    return datetime.now().strftime('%H:%M:%S')


def _format_summary(merged, win_probs, show_win_prob, prev_shares):
    lines = [f"[{_ts()}] {merged['pct_reported']*100:.1f}% reporting"]
    for c in sorted(CANDIDATES, key=lambda x: -merged['actual_share'].get(x, 0)):
        share = merged['actual_share'].get(c, 0.0)
        delta = share - prev_shares.get(c, share)
        delta_str = f" ({delta:+.1f})" if prev_shares else ""
        wp_str = f"  [{win_probs[c]:.1f}%]" if show_win_prob else ""
        lines.append(f"  {c:<16} {share:5.1f}%{delta_str}{wp_str}")
    return "\n".join(lines)


# ── Bot results translator ────────────────────────────────────────────────────

def _build_bot_results(merged, jurisdictions):
    """
    Translates the main loop's merged/jurisdictions dicts into the shape
    that BlueskyBot.post_thread() expects:

        {
            'district': {'candidates': {name: votes}, 'pct_reporting': float},
            'chicago':  {'candidates': {name: votes}, 'pct_reporting': float},
            'cook':     {'candidates': {name: votes}, 'pct_reporting': float},
            'lake':     {'candidates': {name: votes}, 'pct_reporting': float},
            'mchenry':  {'candidates': {name: votes}, 'pct_reporting': float},
        }

    Note: bot expects candidates as {name: int votes} and pct_reporting (not pct_reported).
    """
    bot_results = {
        'district': {
            'candidates':    merged['votes'],           # already {name: int}
            'pct_reporting': merged['pct_reported'],
        }
    }
    for jname in ('chicago', 'cook', 'lake', 'mchenry'):
        jdata = jurisdictions.get(jname, {})
        cands = jdata.get('candidates', {})
        # cands is {name: {'votes': int, 'pct': float}} — unwrap to {name: int}
        bot_results[jname] = {
            'candidates':    {c: cands[c]['votes'] for c in CANDIDATES if c in cands},
            'pct_reporting': jdata.get('pct_reported', 0.0),
        }
    return bot_results


# ── Main loop ─────────────────────────────────────────────────────────────────

def main():
    print("=" * 60)
    print("IL-09 ELECTION NIGHT TRACKER")
    print(f"Started: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print("=" * 60)

    # Load poll baseline
    print(f"\nLoading poll baseline from {POLL_BASELINE_FILE}...")
    poll_params = load_poll_baseline()
    poll_baseline = poll_params['baseline']
    print("Poll baseline loaded:")
    for c in CANDIDATES:
        print(f"  {c:<16} {poll_baseline[c]:.1f}%")

    # Initialise scrapers and bot
    cook_scraper = CookCountyScraper()
    lm_scraper = LakeMcHenryScraper()
    bot = BlueskyBot(dry_run=False)

    # State
    eliminated        = set()
    prev_shares       = {}
    last_post_time    = 0.0
    tick              = 0
    call_fired        = False
    logger            = ElectionLogger()

    print("\nEntering poll loop (Ctrl+C to stop)...\n")

    while True:
        tick += 1
        loop_start = time.time()

        # ── 1. Fetch ──────────────────────────────────────────────────────
        jurisdictions, cook_raw = fetch_all_jurisdictions(cook_scraper, lm_scraper)
        merged = merge_district(jurisdictions)

        # Warn if Cook precinct name match rate drops below 80%
        reported_names = cook_raw.get('reported', set()) if cook_raw else set()
        match_rate = cook_exp.match_rate(reported_names)
        if reported_names and match_rate < 0.80:
            print(f"  ⚠️  Cook precinct name match rate: {match_rate:.0%} "
                  f"— check name format in Cook_County_Scraper.py")

        # ── 2. Simulation ─────────────────────────────────────────────────
        # Cook: use precinct-level blended shares; others: district-wide blend
        if cook_raw and cook_raw.get('reported'):
            cook_blended = cook_exp.blended_shares(cook_raw)
        else:
            cook_blended = None
        blended = build_blended_baseline(
            merged['actual_share'], poll_baseline, merged['pct_reported'],
            cook_blended=cook_blended,
            cook_weight=JURISDICTION_VOTE_WEIGHT['cook'],
        )
        win_probs, ceiling = run_election_night_simulation(blended, poll_params)

        # ── 3. Elimination check ──────────────────────────────────────────
        # Don't fire eliminations until 20% of district is in
        if merged['pct_reported'] >= MIN_REPORTING_FOR_ELIMINATION:
            newly_eliminated = check_eliminations(win_probs, ceiling, eliminated)
        else:
            newly_eliminated = set()
        eliminated |= newly_eliminated

        # ── 3b. Log this tick ────────────────────────────────────────────
        logger.log(tick, merged, win_probs, ceiling, eliminated, call_fired)

        # ── 4. Decide whether to post ─────────────────────────────────────
        show_wp    = thresholds_met(merged)
        now        = time.time()
        time_to_post  = (now - last_post_time) >= POST_INTERVAL_SECONDS
        trigger_elim  = bool(newly_eliminated)
        trigger_call  = any(
            win_probs[c] >= WIN_PROB_CALL_THRESHOLD for c in CANDIDATES
        ) and show_wp

        should_post = time_to_post or trigger_elim or trigger_call

        # ── 5. Console summary ────────────────────────────────────────────
        print(_format_summary(merged, win_probs, show_wp, prev_shares))
        if newly_eliminated:
            print(f"  *** ELIMINATION: {', '.join(newly_eliminated)} ***")

        # ── 6. Post to Bluesky ────────────────────────────────────────────
        if should_post:
            reason = (
                "elimination trigger" if trigger_elim
                else "win-prob trigger" if trigger_call
                else "scheduled"
            )
            print(f"  → Posting to Bluesky ({reason})...")
            try:
                bot_results = _build_bot_results(merged, jurisdictions)

                if trigger_elim:
                    bot.post_eliminations(newly_eliminated, bot_results)

                if trigger_call:
                    winner = max(CANDIDATES, key=lambda c: win_probs[c])
                    bot.post_projected_winner(winner, win_probs[winner], bot_results)
                    call_fired = True
                elif time_to_post:
                    projected = (
                        max(CANDIDATES, key=lambda c: win_probs[c])
                        if show_wp and max(win_probs.values()) >= WIN_PROB_CALL_THRESHOLD
                        else None
                    )
                    bot.post_thread(
                        bot_results,
                        win_prob={c: win_probs[c] / 100.0 for c in CANDIDATES} if show_wp else None,
                        projected_winner=projected,
                    )

                last_post_time = now
            except Exception as e:
                print(f"  ✗ Bluesky post failed: {e}")

        # ── 7. Update state ───────────────────────────────────────────────
        if merged['pct_reported'] > 0:
            prev_shares = dict(merged['actual_share'])

        # ── 8. Sleep until next tick ──────────────────────────────────────
        elapsed = time.time() - loop_start
        sleep_for = max(0, POLL_INTERVAL_SECONDS - elapsed)
        if tick % 10 == 0:
            print(f"  [tick {tick} | loop took {elapsed:.1f}s | sleeping {sleep_for:.1f}s]")
        time.sleep(sleep_for)


if __name__ == '__main__':
    import sys
    if '--preflight' in sys.argv:
        try:
            preflight()
        except KeyboardInterrupt:
            print("\nPreflight cancelled.")
    else:
        try:
            main()
        except KeyboardInterrupt:
            print("\n\nTracker stopped.")


def preflight():
    """
    Dry-run one full tick. Posts nothing to Bluesky.
    Run with:  python main.py --preflight
    """
    print("=" * 60)
    print("IL-09 PREFLIGHT CHECK")
    print(f"Time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print("=" * 60)

    # 1. Poll baseline
    print(f"\n[1/5] Loading poll baseline...")
    try:
        poll_params = load_poll_baseline()
        poll_baseline = poll_params['baseline']
        print(f"  OK Loaded")
        for c in CANDIDATES:
            print(f"     {c:<16} {poll_baseline[c]:.1f}%")
    except Exception as e:
        print(f"  FAILED: {e}")
        return

    # 2. Scrapers
    print(f"\n[2/5] Initialising scrapers...")
    cook_scraper = CookCountyScraper()
    lm_scraper   = LakeMcHenryScraper()
    print(f"  OK Cook and Lake/McHenry scrapers ready")

    # 3. Fetch
    print(f"\n[3/5] Fetching all jurisdictions...")
    jurisdictions = fetch_all_jurisdictions(cook_scraper, lm_scraper)
    for jname, jdata in jurisdictions.items():
        pct = jdata.get('pct_reported', 0.0)
        total_votes = sum(
            jdata['candidates'][c]['votes']
            for c in CANDIDATES
            if c in jdata['candidates']
        )
        status = "OK  " if jdata['candidates'] else "WARN"
        print(f"  [{status}] {jname.upper():<10} pct_reported={pct:.1%}  total_votes={total_votes:,}")
        if total_votes > 0:
            top = sorted(
                [(c, jdata['candidates'][c]['votes'])
                 for c in CANDIDATES if c in jdata['candidates']],
                key=lambda x: -x[1]
            )[:3]
            for cand, votes in top:
                print(f"         {cand:<16} {votes:,}")
        else:
            print(f"         (zero votes -- expected before polls close)")

    # 4. Merge + simulate
    print(f"\n[4/5] Merging and simulating (1k iterations)...")
    merged = merge_district(jurisdictions)
    print(f"  District pct_reported: {merged['pct_reported']:.1%}")
    blended = build_blended_baseline(
        merged['actual_share'], poll_baseline, merged['pct_reported']
    )
    win_probs, ceiling = run_election_night_simulation(blended, poll_params, n=1_000)
    print(f"  Win probs (illustrative -- poll prior only until votes come in):")
    for c in sorted(CANDIDATES, key=lambda x: -win_probs[x]):
        print(f"     {c:<16} {win_probs[c]:.1f}%  (p90: {ceiling[c]:.1f}%)")

    # 5. Bot
    print(f"\n[5/5] Testing Bluesky bot (dry_run=True)...")
    try:
        bot = BlueskyBot(dry_run=True)
        bot_results = _build_bot_results(merged, jurisdictions)
        bot.post_thread(bot_results, win_prob=None, projected_winner=None)
        print(f"  OK Bot dry-run complete -- check post text above")
    except Exception as e:
        print(f"  FAILED: {e}")

    print(f"\n{'=' * 60}")
    print(f"PREFLIGHT COMPLETE -- {datetime.now().strftime('%H:%M:%S')}")
    print(f"{'=' * 60}")
    print(f"\nAll good? Run:  python main.py")
    print(f"Chicago stub?  Build chicago_boe_scraper.py first.")